---
###########################
# Ansible Playbook: Roles - main.yml
#   Creates WebNode by orchestrating diffrent roles and tasks.
# Source Repository: https://github.com/????
###########################

- name: Get 1st playbook and play it.
  ansible.builtin.import_playbook: A_pre_ip_change.yml

- name: Get 2nd playbook and play it.
  ansible.builtin.import_playbook: B_post_ip_change.yml
