---
####
# SECRETS SHADOW FILE - THIS FILE BY ITSELF IS NOT TO BE USED IN ANSIBLE CONFIGURATION..........
################################################################################################
# This is a shadow file for the actual secrets file. It only lists important variable names (not the values)
# You will need to create the following 2 files. These are already added in .gitignore file.
# ./secrets.yml   (You may choose not to add this to .gitignore - can be be version controlled)
# ./vault_pass
# References: https://medium.com/devops-process-and-tools/manage-secrets-with-ansible-vault-d0528b7a99f4
#             https://www.redhat.com/sysadmin/ansible-playbooks-secrets
################################################################################################
# $ ansible-vault decrypt secrets.yml
# $ ansible-vault encrypt secrets.yml
####
# Passowrd Hashing for ansible.builtin.user module:
#     ansible all -i localhost, -m debug -a "msg={{ 'mypassword' | password_hash('sha512', 'mysecretsalt') }}"
#       OR
#     mkpasswd --method=sha-512
####
su_vault_vmuser1: xxxx
su_vault_vmpwd1: xxxx
su_vault_vmuser2: xxxx
su_vault_vmpwd2: xxxx
su_vault_mariadb_user: xxxx
su_vault_mariadb_pwd: xxxx
su_vault_mariadb_port: xxxx
su_vault_db_name: xxxx
wp_admin_id: xxxx
wp_admin_pwd: xxxx
wp_admin_email: xxxx
su_certbot_domain_name: xxxx
dynu_login: xxxx
dynu_password: xxxx
dynu_server: xxxx
dynu_list_domain_names:
  - xxx.com
  - yyy.ca